### ISSUE TITLE
Carousel

### ISSUE THREAD

**Issue by nemo256** [nemo256/hotel#2]
Carousel **arrows** not aligned, **overlay** with navbar (z-index) and **not responsive** on mobile screens.

**Comment by ouadjih** [comment]
I tried to fix it , i think its better now ,more responsive , check it out , i don't know how to set height of  Stack or flex to fit it to screen (its getting bigger then the screen), i tried with height attribute and it doesn't work ,  i added services and its not done just set the services array i'll add icons  and more services more tommorw

**Comment by nemo256** [comment]
Fixed.
